### ISSUE TITLE
testParseProcessDefinitionXXE breaks build

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton#198]
**Describe the bug**

I'm experiencing a failure running a normal Maven build on current `main`(#9cc4fd71)

```
[ERROR] Failures: 
[ERROR]   BpmnParseTest.shouldPreventXxeProcessing:1212 
Expecting throwable message:
  "ENGINE-09003 Could not parse 'org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testParseProcessDefinitionXXE.bpmn20.xml'. DOCTYPE ist nicht zulässig, wenn das Feature "http://apache.org/xml/features/disallow-doctype-decl" auf "true" gesetzt ist."
to contain:
  "DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true."
but did not.

Throwable that failed the check:

org.operaton.bpm.engine.ProcessEngineException: ENGINE-09003 Could not parse 'org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testParseProcessDefinitionXXE.bpmn20.xml'. DOCTYPE ist nicht zulässig, wenn das Feature "http://apache.org/xml/features/disallow-doctype-decl" auf "true" gesetzt ist.
        at org.operaton.bpm.engine.impl.util.EngineUtilLogger.parsingFailureException(EngineUtilLogger.java:54)
        at org.operaton.bpm.engine.impl.util.xml.Parse.execute(Parse.java:150)
        at org.operaton.bpm.engine.impl.bpmn.parser.BpmnParse.execute(BpmnParse.java:334)
        at org.operaton.bpm.engine.impl.bpmn.deployer.BpmnDeployer.transformDefinitions(BpmnDeployer.java:106)
        at org.operaton.bpm.engine.impl.AbstractDefinitionDeployer.transformResource(AbstractDefinitionDeployer.java:99)
        at org.operaton.bpm.engine.impl.AbstractDefinitionDeployer.parseDefinitionResources(AbstractDefinitionDeployer.java:74)
        at org.operaton.bpm.engine.impl.AbstractDefinitionDeployer.deploy(AbstractDefinitionDeployer.java:64)
        at org.operaton.bpm.engine.impl.persistence.deploy.cache.CacheDeployer$1.call(CacheDeployer.java:54)
        at org.operaton.bpm.engine.impl.persistence.deploy.cache.CacheDeployer$1.call(CacheDeployer.java:51)
        at org.operaton.bpm.engine.impl.interceptor.CommandContext.runWithoutAuthorization(CommandContext.java:554)
        at org.operaton.bpm.engine.impl.interceptor.CommandContext.runWithoutAuthorization(CommandContext.java:542)
        at org.operaton.bpm.engine.impl.persistence.deploy.cache.CacheDeployer.deploy(CacheDeployer.java:51)
        at org.operaton.bpm.engine.impl.persistence.deploy.cache.DeploymentCache.deploy(DeploymentCache.java:71)
        at org.operaton.bpm.engine.impl.persistence.entity.DeploymentManager.insertDeployment(DeploymentManager.java:64)
        at org.operaton.bpm.engine.impl.cmd.DeployCmd.deploy(DeployCmd.java:258)
        at org.operaton.bpm.engine.impl.cmd.DeployCmd.lambda$doExecute$0(DeployCmd.java:155)
        at org.operaton.bpm.engine.impl.interceptor.CommandContext.runWithoutAuthorization(CommandContext.java:554)
        at org.operaton.bpm.engine.impl.interceptor.CommandContext.runWithoutAuthorization(CommandContext.java:542)
        at org.operaton.bpm.engine.impl.cmd.DeployCmd.doExecute(DeployCmd.java:141)
        at org.operaton.bpm.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:101)
        at org.operaton.bpm.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:81)
        at org.operaton.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:28)
        at org.operaton.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:111)
        at org.operaton.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70)
        at org.operaton.bpm.engine.impl.interceptor.CommandCounterInterceptor.execute(CommandCounterInterceptor.java:34)
        at org.operaton.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33)
        at org.operaton.bpm.engine.impl.interceptor.ExceptionCodeInterceptor.execute(ExceptionCodeInterceptor.java:55)
        at org.operaton.bpm.engine.impl.RepositoryServiceImpl.deployWithResult(RepositoryServiceImpl.java:104)
        at org.operaton.bpm.engine.impl.repository.DeploymentBuilderImpl.deployWithResult(DeploymentBuilderImpl.java:270)
        at org.operaton.bpm.engine.impl.repository.DeploymentBuilderImpl.deploy(DeploymentBuilderImpl.java:266)
        at org.operaton.bpm.engine.test.bpmn.parse.BpmnParseTest.lambda$shouldPreventXxeProcessing$0(BpmnParseTest.java:1210)
        at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:63)
        at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:904)
        at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1470)
        at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1313)
        at org.operaton.bpm.engine.test.bpmn.parse.BpmnParseTest.shouldPreventXxeProcessing(BpmnParseTest.java:1207)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.operaton.bpm.engine.test.ProcessEngineRule$1.evaluate(ProcessEngineRule.java:191)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 10; DOCTYPE ist nicht zulässig, wenn das Feature "http://apache.org/xml/features/disallow-doctype-decl" auf "true" gesetzt ist.
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1251)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
        at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
        at org.operaton.bpm.engine.impl.util.xml.Parse.execute(Parse.java:148)
        ... 68 more

[ERROR]   BpmnParseTest.testInvalidSubProcessWithConditionalStartEvent:163 expected presence of [The content of element 'bpmn2:conditionalEventDefinition' is not complete.], but was [ENGINE-09005 Could not parse BPMN process. Errors: 
* cvc-complex-type.2.4.b: Content des Elements 'bpmn2:conditionalEventDefinition' ist nicht vollständig. '{"http://www.omg.org/spec/BPMN/20100524/MODEL":documentation, "http://www.omg.org/spec/BPMN/20100524/MODEL":extensionElements, "http://www.omg.org/spec/BPMN/20100524/MODEL":condition}' wird erwartet. | resource org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testInvalidSubProcessWithConditionalStartEvent.bpmn | line 24 | column 78
* conditionalEventDefinition is not allowed on start event within a subprocess | resource org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testInvalidSubProcessWithConditionalStartEvent.bpmn | line 24 | column 78]
[ERROR]   BpmnParseTest.testInvalidTransactionWithConditionalStartEvent:263 expected presence of [The content of element 'bpmn2:conditionalEventDefinition' is not complete.], but was [ENGINE-09005 Could not parse BPMN process. Errors: 
* cvc-complex-type.2.4.b: Content des Elements 'bpmn2:conditionalEventDefinition' ist nicht vollständig. '{"http://www.omg.org/spec/BPMN/20100524/MODEL":documentation, "http://www.omg.org/spec/BPMN/20100524/MODEL":extensionElements, "http://www.omg.org/spec/BPMN/20100524/MODEL":condition}' wird erwartet. | resource org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testInvalidTransactionWithConditionalStartEvent.bpmn | line 15 | column 78
* conditionalEventDefinition is not allowed on start event within a subprocess | resource org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testInvalidTransactionWithConditionalStartEvent.bpmn | line 15 | column 78]
[ERROR]   BpmnParseTest.testParseInvalidConditionalBoundaryEvent:722->parseInvalidConditionalEvent:711 expected presence of [The content of element 'bpmn:conditionalEventDefinition' is not complete.], but was [ENGINE-09005 Could not parse BPMN process. Errors: 
* cvc-complex-type.2.4.b: Content des Elements 'bpmn:conditionalEventDefinition' ist nicht vollständig. '{"http://www.omg.org/spec/BPMN/20100524/MODEL":documentation, "http://www.omg.org/spec/BPMN/20100524/MODEL":extensionElements, "http://www.omg.org/spec/BPMN/20100524/MODEL":condition}' wird erwartet. | resource org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testParseInvalidConditionalBoundaryEvent.bpmn | line 22 | column 41
* Conditional event must contain an expression for evaluation. | resource org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testParseInvalidConditionalBoundaryEvent.bpmn | line 22 | column 41]
[ERROR]   BpmnParseTest.testParseInvalidEventSubprocessConditionalStartEvent:763->parseInvalidConditionalEvent:711 expected presence of [The content of element 'bpmn:conditionalEventDefinition' is not complete.], but was [ENGINE-09005 Could not parse BPMN process. Errors: 
* cvc-complex-type.2.4.b: Content des Elements 'bpmn:conditionalEventDefinition' ist nicht vollständig. '{"http://www.omg.org/spec/BPMN/20100524/MODEL":documentation, "http://www.omg.org/spec/BPMN/20100524/MODEL":extensionElements, "http://www.omg.org/spec/BPMN/20100524/MODEL":condition}' wird erwartet. | resource org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testParseInvalidEventSubprocessConditionalStartEvent.bpmn | line 19 | column 43
* Conditional event must contain an expression for evaluation. | resource org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testParseInvalidEventSubprocessConditionalStartEvent.bpmn | line 19 | column 43]
[ERROR]   BpmnParseTest.testParseInvalidIntermediateConditionalEvent:749->parseInvalidConditionalEvent:711 expected presence of [The content of element 'bpmn:conditionalEventDefinition' is not complete.], but was [ENGINE-09005 Could not parse BPMN process. Errors: 
* cvc-complex-type.2.4.b: Content des Elements 'bpmn:conditionalEventDefinition' ist nicht vollständig. '{"http://www.omg.org/spec/BPMN/20100524/MODEL":documentation, "http://www.omg.org/spec/BPMN/20100524/MODEL":extensionElements, "http://www.omg.org/spec/BPMN/20100524/MODEL":condition}' wird erwartet. | resource org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testParseInvalidIntermediateConditionalEvent.bpmn | line 11 | column 41
* Conditional event must contain an expression for evaluation. | resource org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testParseInvalidIntermediateConditionalEvent.bpmn | line 11 | column 41]
[ERROR]   BpmnParseTest.testXmlParsingErrors:360 expected presence of [The end-tag for element type "bpmndi:BPMNLabel" must end with a '>' delimiter], but was [ENGINE-09003 Could not parse 'org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.testXMLParsingErrors.bpmn'. Endtag für Elementtyp "bpmndi:BPMNLabel" muss mit einem ">"-Begrenzungszeichen enden.]
[INFO] 
[ERROR] Tests run: 15757, Failures: 7, Errors: 0, Skipped: 73
```

**To Reproduce**

Run on `main` branch:
```./mvnw clean verify```

**Comment by javahippie** [comment]
Can reproduce. Interesting, that this did not break in the main branches pipeline.

**Comment by javahippie** [comment]
I re-ran the pipeline on main and it still works, so the issue seems to be platform-dependent: https://github.com/operaton/operaton/actions/runs/11816824096

**Comment by javahippie** [comment]
This is locale-specific: The test expects the error message in English, but receives the error message in German.

In the last commit I see that `-Duser.language=en -Duser.region=US` was moved from `maven-surefire-plugin` configuration to the `surefire.argLine` property, but it is not referenced in `engine/pom.xml` (the failing project) or the plugin configuration of a parent, so now the tests for this module (at least) are running in the default OS locale, which is German in our case.

**Comment by kthoms** [comment]
@javahippie The Surefire configuration should use the default setting from the Parent POM, which sets the locale to english. If this is not the case, then this was not my intention with defining `surefire.argLine` amd make it overridable.

Thanks for this pointer, this will be enough to fix it. I'll provide a fix.

**Comment by kthoms** [comment]
I'm wondering why I did not experienced that before. I executed so many builds while working on the surefire.argLine change. 🤷

**Comment by kthoms** [comment]
I think when a test is locale / time specific, it should itself make sure that it is properly set up and not depending on build settings. I will have a look at the test first.

**Comment by kthoms** [comment]
I'm able to reproduce this in the IDE.

![Screenshot 310](https://github.com/user-attachments/assets/1f623477-75f0-42cd-b01b-ec2af0bbcd35)

**Comment by kthoms** [comment]
It was indeed that one test that needs to set an explicit locale. I'm wondering why german was used here by the test. I did not see where this would have been set.
