### ISSUE TITLE
NullPointerException in test execution of operaton-external-task-client (flaky)

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton#251]
**Describe the bug**
I'm exeperiencing sometimes failing builds in the integration tests of module `operaton-external-task-client`.

```
[INFO] --- failsafe:3.5.1:integration-test (default) @ operaton-external-task-client ---
[INFO] Failsafe report directory: /Users/karstenthoms/Development/projects/operaton/clients/java/client/target/failsafe-reports
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.operaton.bpm.client.variable.pa.PaSerializationIT
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.198 s <<< FAILURE! -- in org.operaton.bpm.client.variable.pa.PaSerializationIT
[ERROR] org.operaton.bpm.client.variable.pa.PaSerializationIT.shouldSelectSequenceFlowAndCompleteProcessInstance_XmlSerialization -- Time elapsed: 0.183 s <<< ERROR!
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(org.apache.hc.core5.http.ClassicHttpRequest, org.apache.hc.core5.http.io.HttpClientResponseHandler)" because "this.httpClient" is null
        at org.operaton.bpm.client.rule.EngineRule.startProcessInstance(EngineRule.java:304)
        at org.operaton.bpm.client.rule.EngineRule.startProcessInstanceByKey(EngineRule.java:227)
        at org.operaton.bpm.client.variable.pa.PaSerializationIT.setup(PaSerializationIT.java:91)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        Suppressed: java.lang.NullPointerException: Cannot invoke "org.operaton.bpm.client.dto.ProcessInstanceDto.getId()" because "this.processInstance" is null
                at org.operaton.bpm.client.variable.pa.PaSerializationIT.tearDown(PaSerializationIT.java:99)
                ... 3 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(org.apache.hc.core5.http.ClassicHttpRequest, org.apache.hc.core5.http.io.HttpClientResponseHandler)" because "this.httpClient" is null
        at org.operaton.bpm.client.rule.EngineRule.executeRequest(EngineRule.java:375)
        at org.operaton.bpm.client.rule.EngineRule.startProcessInstance(EngineRule.java:301)
        ... 5 more

[ERROR] org.operaton.bpm.client.variable.pa.PaSerializationIT.shouldSelectSequenceFlowAndCompleteProcessInstance_JsonSerialization -- Time elapsed: 0.002 s <<< ERROR!
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(org.apache.hc.core5.http.ClassicHttpRequest, org.apache.hc.core5.http.io.HttpClientResponseHandler)" because "this.httpClient" is null
        at org.operaton.bpm.client.rule.EngineRule.startProcessInstance(EngineRule.java:304)
        at org.operaton.bpm.client.rule.EngineRule.startProcessInstanceByKey(EngineRule.java:227)
        at org.operaton.bpm.client.variable.pa.PaSerializationIT.setup(PaSerializationIT.java:91)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        Suppressed: java.lang.NullPointerException: Cannot invoke "org.operaton.bpm.client.dto.ProcessInstanceDto.getId()" because "this.processInstance" is null
                at org.operaton.bpm.client.variable.pa.PaSerializationIT.tearDown(PaSerializationIT.java:99)
                ... 3 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(org.apache.hc.core5.http.ClassicHttpRequest, org.apache.hc.core5.http.io.HttpClientResponseHandler)" because "this.httpClient" is null
        at org.operaton.bpm.client.rule.EngineRule.executeRequest(EngineRule.java:375)
        at org.operaton.bpm.client.rule.EngineRule.startProcessInstance(EngineRule.java:301)
        ... 5 more

[ERROR] org.operaton.bpm.client.variable.pa.PaSerializationIT.shouldSelectSequenceFlowAndCompleteProcessInstance_JavaSerialization -- Time elapsed: 0.002 s <<< ERROR!
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(org.apache.hc.core5.http.ClassicHttpRequest, org.apache.hc.core5.http.io.HttpClientResponseHandler)" because "this.httpClient" is null
        at org.operaton.bpm.client.rule.EngineRule.startProcessInstance(EngineRule.java:304)
        at org.operaton.bpm.client.rule.EngineRule.startProcessInstanceByKey(EngineRule.java:227)
        at org.operaton.bpm.client.variable.pa.PaSerializationIT.setup(PaSerializationIT.java:91)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        Suppressed: java.lang.NullPointerException: Cannot invoke "org.operaton.bpm.client.dto.ProcessInstanceDto.getId()" because "this.processInstance" is null
                at org.operaton.bpm.client.variable.pa.PaSerializationIT.tearDown(PaSerializationIT.java:99)
                ... 3 more
```

**To Reproduce**
```./mvnw clean verify```
The issue is not always reproducible, in most runs it just works.

**Expected behavior**
Build execution is always successful.

**Comment by kthoms** [comment]
This is annoying and blocks builds. I will now disable these tests for now. In the context of this bug the disabled tests have to be activated again.
I will configure the `maven-failsafe-plugin` in `clients/java/client/pom.xml` to skip.

**Comment by javahippie** [comment]
In the debugger, you can see that the instance of EngineRule which is called by the tests is a different instance than the one being initlialized

**Comment by javahippie** [comment]
I have started a Draft PR here: https://github.com/operaton/operaton/pull/260

The error scenarios fail now, but on my machine all `client` tests are successfully execution any time. The failing error scenarios are to be debugged later (running out of time rn)

**Comment by kthoms** [comment]
The `integration-test` phase is actually _before_ `verify`. Makes sense, `verify` is _"run any checks to verify the package is valid and meets quality criteria"_ , so before that integration tests should run.

`install` just installs the verified package.

**Comment by javahippie** [comment]
You are right, but then I'm thoroughly confused now. I'm seeing a lot of pipeline builds which do not execute the failsafe plugin and thought this was the common denominator. Will keep looking, then.

**Comment by javahippie** [comment]
@kthoms Could you please verify my following assumption on your machine? I think the External Task Client Java module is not considered when using the Maven Wrapper.

I am using the Maven Build Plan plugin to debug this:

```
./mvnw fr.jcgay.maven.plugins:buildplan-maven-plugin:list

...

[INFO] --< org.operaton.bpm.springboot:operaton-bpm-spring-boot-starter-external-task-client >--
[INFO] Building Operaton - Spring Boot Starter - Client - Spring Boot 1.0.0-beta-2 [71/127]
[INFO]   from spring-boot-starter/starter-client/spring-boot/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
...
```

```
mvn fr.jcgay.maven.plugins:buildplan-maven-plugin:list

[INFO] -----------< org.operaton.bpm:operaton-external-task-client >-----------
[INFO] Building Operaton - Java External Task Client - Client 1.0.0-beta-2 [69/127]
[INFO]   from clients/java/client/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- buildplan:1.5:list (default-cli) @ operaton-external-task-client ---
[WARNING] Parameter 'wait' is unknown for plugin 'cargo-maven3-plugin:1.10.15:start (start-container)'
[WARNING] Parameter 'wait' is unknown for plugin 'cargo-maven3-plugin:1.10.15:stop (stop-container)'
[INFO] Build Plan for Operaton - Java External Task Client - Client: 
---------------------------------------------------------------------------------------------------------
PLUGIN                          | PHASE                  | ID                          | GOAL            
---------------------------------------------------------------------------------------------------------
maven-enforcer-plugin           | validate               | enforce-default             | enforce         
maven-dependency-plugin         | generate-resources     | default                     | unpack          
maven-resources-plugin          | process-resources      | default-resources           | resources       
maven-compiler-plugin           | compile                | default-compile             | compile         
build-helper-maven-plugin       | generate-test-sources  | add-it-source               | add-test-source 
maven-resources-plugin          | process-test-resources | default-testResources       | testResources   
maven-compiler-plugin           | test-compile           | default-testCompile         | testCompile     
maven-surefire-plugin           | test                   | default-test                | test            
maven-jar-plugin                | package                | default-jar                 | jar             
cargo-maven3-plugin             | pre-integration-test   | start-container             | start           
maven-failsafe-plugin           | integration-test       | default                     | integration-test
cargo-maven3-plugin             | post-integration-test  | stop-container              | stop            
maven-failsafe-plugin           | verify                 | default                     | verify          
maven-install-plugin            | install                | default-install             | install         
central-publishing-maven-plugin | deploy                 | injected-central-publishing | publish         
[INFO] 

```

Both Maven versions are 3.9.9

**Comment by javahippie** [comment]
Storing the relevant part of a build here which did not execute the failsafe plugin:

```
[INFO] -----------< org.operaton.bpm:operaton-external-task-client >-----------
[INFO] Building Operaton - Java External Task Client - Client 1.0.0-beta-2 [66/128]
[INFO]   from clients/java/client/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- enforcer:3.5.0:enforce (enforce-default) @ operaton-external-task-client ---
[INFO] Rule 2: org.apache.maven.enforcer.rules.RequireMatchingCoordinates passed
[INFO] 
[INFO] --- jacoco:0.8.12:prepare-agent (prepare-agent) @ operaton-external-task-client ---
[INFO] jacoco.argLine set to -javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.12/org.jacoco.agent-0.8.12-runtime.jar=destfile=/home/runner/work/operaton/operaton/clients/java/client/target/jacoco.exec
[INFO] 
[INFO] --- dependency:3.8.1:unpack (default) @ operaton-external-task-client ---
[INFO] Configured Artifact: org.operaton.bpm.tomcat:operaton-tomcat-assembly:1.0.0-beta-2:tar.gz
[INFO] Expanding: /home/runner/work/operaton/operaton/distro/tomcat/assembly/target/operaton-tomcat-assembly-1.0.0-beta-2.tar.gz into /home/runner/work/operaton/operaton/clients/java/client/target/operaton-tomcat
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ operaton-external-task-client ---
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.13.0:compile (default-compile) @ operaton-external-task-client ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 98 source files with javac [debug target 17] to target/classes
[INFO] /home/runner/work/operaton/operaton/clients/java/client/src/main/java/org/operaton/bpm/client/impl/RequestExecutor.java: Some input files use unchecked or unsafe operations.
[INFO] /home/runner/work/operaton/operaton/clients/java/client/src/main/java/org/operaton/bpm/client/impl/RequestExecutor.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- build-helper:3.6.0:add-test-source (add-it-source) @ operaton-external-task-client ---
[INFO] Test Source directory: /home/runner/work/operaton/operaton/clients/java/client/src/it/java added.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ operaton-external-task-client ---
[INFO] Copying 7 resources from src/it/resources to target/test-classes
[INFO] skip non existing resourceDirectory /home/runner/work/operaton/operaton/clients/java/client/src/test/resources
[INFO] 
[INFO] --- compiler:3.13.0:testCompile (default-testCompile) @ operaton-external-task-client ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 40 source files with javac [debug target 17] to target/test-classes
[INFO] /home/runner/work/operaton/operaton/clients/java/client/src/it/java/org/operaton/bpm/client/client/ClientIT.java: Some input files use or override a deprecated API.
[INFO] /home/runner/work/operaton/operaton/clients/java/client/src/it/java/org/operaton/bpm/client/client/ClientIT.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- surefire:3.5.1:test (default-test) @ operaton-external-task-client ---
[INFO] Surefire report directory: /home/runner/work/operaton/operaton/clients/java/client/target/surefire-reports
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.operaton.bpm.client.backoff.ExponentialBackoffStrategyTest
[INFO] Running org.operaton.bpm.client.backoff.ExponentialErrorBackoffStrategyTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.106 s -- in org.operaton.bpm.client.backoff.ExponentialBackoffStrategyTest
[INFO] Running org.operaton.bpm.client.impl.ExternalTaskClientBuilderImplTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.104 s -- in org.operaton.bpm.client.backoff.ExponentialErrorBackoffStrategyTest
[INFO] Running org.operaton.bpm.client.task.ExternalTaskImplTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.123 s -- in org.operaton.bpm.client.task.ExternalTaskImplTest
[INFO] Running org.operaton.bpm.client.variable.DateValueMapperTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.026 s -- in org.operaton.bpm.client.variable.DateValueMapperTest
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.381 s -- in org.operaton.bpm.client.impl.ExternalTaskClientBuilderImplTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jacoco:0.8.12:report (report) @ operaton-external-task-client ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO] 
[INFO] --- jar:3.4.2:jar (default-jar) @ operaton-external-task-client ---
Warning:   Parameter 'useDefaultManifestFile' (user property 'jar.useDefaultManifestFile') is deprecated: For version 3.0.0 this parameter is only defined here to break the build if you use it!
[INFO] Building jar: /home/runner/work/operaton/operaton/clients/java/client/target/operaton-external-task-client-1.0.0-beta-2.jar
```

**Comment by javahippie** [comment]
And for comparison, a build from my local machine which did execute failsafe:

```
[INFO] -----------< org.operaton.bpm:operaton-external-task-client >-----------
[INFO] Building Operaton - Java External Task Client - Client 1.0.0-beta-2 [69/127]
[INFO]   from clients/java/client/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] Parameter 'wait' is unknown for plugin 'cargo-maven3-plugin:1.10.15:start (start-container)'
[WARNING] Parameter 'wait' is unknown for plugin 'cargo-maven3-plugin:1.10.15:stop (stop-container)'
[INFO] 
[INFO] --- clean:3.4.0:clean (default-clean) @ operaton-external-task-client ---
[INFO] Deleting /Users/zoeller/sources/operaton/operaton-bpm-platform/clients/java/client/target
[INFO] 
[INFO] --- enforcer:3.5.0:enforce (enforce-default) @ operaton-external-task-client ---
[INFO] Rule 2: org.apache.maven.enforcer.rules.RequireMatchingCoordinates passed
[INFO] 
[INFO] --- dependency:3.8.1:unpack (default) @ operaton-external-task-client ---
[INFO] Configured Artifact: org.operaton.bpm.tomcat:operaton-tomcat-assembly:1.0.0-beta-2:tar.gz
[INFO] Expanding: /Users/zoeller/sources/operaton/operaton-bpm-platform/distro/tomcat/assembly/target/operaton-tomcat-assembly-1.0.0-beta-2.tar.gz into /Users/zoeller/sources/operaton/operaton-bpm-platform/clients/java/client/target/operaton-tomcat
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ operaton-external-task-client ---
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.13.0:compile (default-compile) @ operaton-external-task-client ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 98 source files with javac [debug target 17] to target/classes
[INFO] /Users/zoeller/sources/operaton/operaton-bpm-platform/clients/java/client/src/main/java/org/operaton/bpm/client/impl/RequestExecutor.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/zoeller/sources/operaton/operaton-bpm-platform/clients/java/client/src/main/java/org/operaton/bpm/client/impl/RequestExecutor.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- build-helper:3.6.0:add-test-source (add-it-source) @ operaton-external-task-client ---
[INFO] Test Source directory: /Users/zoeller/sources/operaton/operaton-bpm-platform/clients/java/client/src/it/java added.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ operaton-external-task-client ---
[INFO] Copying 7 resources from src/it/resources to target/test-classes
[INFO] skip non existing resourceDirectory /Users/zoeller/sources/operaton/operaton-bpm-platform/clients/java/client/src/test/resources
[INFO] 
[INFO] --- compiler:3.13.0:testCompile (default-testCompile) @ operaton-external-task-client ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 40 source files with javac [debug target 17] to target/test-classes
[INFO] /Users/zoeller/sources/operaton/operaton-bpm-platform/clients/java/client/src/it/java/org/operaton/bpm/client/client/ClientIT.java: Some input files use or override a deprecated API.
[INFO] /Users/zoeller/sources/operaton/operaton-bpm-platform/clients/java/client/src/it/java/org/operaton/bpm/client/client/ClientIT.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- surefire:3.5.1:test (default-test) @ operaton-external-task-client ---
[INFO] Surefire report directory: /Users/zoeller/sources/operaton/operaton-bpm-platform/clients/java/client/target/surefire-reports
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.operaton.bpm.client.impl.ExternalTaskClientBuilderImplTest
[INFO] Running org.operaton.bpm.client.backoff.ExponentialBackoffStrategyTest
[INFO] Running org.operaton.bpm.client.backoff.ExponentialErrorBackoffStrategyTest
[INFO] Running org.operaton.bpm.client.task.ExternalTaskImplTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.079 s -- in org.operaton.bpm.client.backoff.ExponentialBackoffStrategyTest
[INFO] Running org.operaton.bpm.client.variable.DateValueMapperTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.078 s -- in org.operaton.bpm.client.backoff.ExponentialErrorBackoffStrategyTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.112 s -- in org.operaton.bpm.client.task.ExternalTaskImplTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.067 s -- in org.operaton.bpm.client.variable.DateValueMapperTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.908 s -- in org.operaton.bpm.client.impl.ExternalTaskClientBuilderImplTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jar:3.4.2:jar (default-jar) @ operaton-external-task-client ---
[WARNING]  Parameter 'useDefaultManifestFile' (user property 'jar.useDefaultManifestFile') is deprecated: For version 3.0.0 this parameter is only defined here to break the build if you use it!
[INFO] Building jar: /Users/zoeller/sources/operaton/operaton-bpm-platform/clients/java/client/target/operaton-external-task-client-1.0.0-beta-2.jar
[INFO] 
[INFO] --- cargo:1.10.15:start (start-container) @ operaton-external-task-client ---
[INFO] 
[INFO] --- failsafe:3.5.1:integration-test (default) @ operaton-external-task-client ---
[INFO] Failsafe report directory: /Users/zoeller/sources/operaton/operaton-bpm-platform/clients/java/client/target/failsafe-reports
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.operaton.bpm.client.client.ClientIT
[INFO] Tests run: 33, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.459 s -- in org.operaton.bpm.client.client.ClientIT
[INFO] Running org.operaton.bpm.client.task.ExternalTaskCustomExtensionPropertiesIT
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.404 s -- in org.operaton.bpm.client.task.ExternalTaskCustomExtensionPropertiesIT
[INFO] Running org.operaton.bpm.client.task.ExternalTaskHandlerIT
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.694 s -- in org.operaton.bpm.client.task.ExternalTaskHandlerIT
[INFO] Running org.operaton.bpm.client.topic.TopicSubscriptionIT
[INFO] Tests run: 33, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.330 s -- in org.operaton.bpm.client.topic.TopicSubscriptionIT
[INFO] Running org.operaton.bpm.client.variable.FileSerializationIT
[ERROR] Tests run: 16, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.695 s <<< FAILURE! -- in org.operaton.bpm.client.variable.FileSerializationIT
[ERROR] org.operaton.bpm.client.variable.FileSerializationIT.shouldFailWhenCompletingWihtDeferredFileValue -- Time elapsed: 0.125 s <<< FAILURE!
java.lang.AssertionError: 

Expecting code to raise a throwable.
        at org.operaton.bpm.client.variable.FileSerializationIT.shouldFailWhenCompletingWihtDeferredFileValue(FileSerializationIT.java:574)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... 
```

**Comment by javahippie** [comment]
The Maven Buildplan Plugin also lists the surefire plugin should be executed in the default phase: 

```
[INFO] Build Plan for Operaton - Java External Task Client - Client: 
---------------------------------------------------------------------------------------------------------
PLUGIN                          | PHASE                  | ID                          | GOAL            
---------------------------------------------------------------------------------------------------------
maven-enforcer-plugin           | validate               | enforce-default             | enforce         
jacoco-maven-plugin             | initialize             | prepare-agent               | prepare-agent   
maven-dependency-plugin         | generate-resources     | default                     | unpack          
maven-resources-plugin          | process-resources      | default-resources           | resources       
maven-compiler-plugin           | compile                | default-compile             | compile         
build-helper-maven-plugin       | generate-test-sources  | add-it-source               | add-test-source 
maven-resources-plugin          | process-test-resources | default-testResources       | testResources   
maven-compiler-plugin           | test-compile           | default-testCompile         | testCompile     
maven-surefire-plugin           | test                   | default-test                | test            
jacoco-maven-plugin             | test                   | report                      | report          
maven-jar-plugin                | package                | default-jar                 | jar             
cargo-maven3-plugin             | pre-integration-test   | start-container             | start           
maven-failsafe-plugin           | integration-test       | default                     | integration-test
cargo-maven3-plugin             | post-integration-test  | stop-container              | stop            
maven-failsafe-plugin           | verify                 | default                     | verify          
maven-install-plugin            | install                | default-install             | install         
central-publishing-maven-plugin | deploy                 | injected-central-publishing | publish         
```

**Comment by kthoms** [comment]
I saw that the build is executed with phase `package` on main. That's a bug. It must be `verify` at least.

**Comment by javahippie** [comment]
And *now* I'm wondering why I did not see this, maybe this was too late in the evening. At least I found new debugging tools. Thanks, will make the change.
